'Colecionável Recebido!': '',
'Coleção: ': '',
'window': '',
'Nome': '',
'Conectados': '',
'Erro': '',
'Nenhum jogador encontrado.': '',
'Dados do jogo não encontrados.': '',
'Houve um problema ao buscar os dados do jogo.': '',
'Nenhum jogador disponível': '',
'Dados dos Jogadores': '',
'Fechar': '',
'Trilha de EXP': '',
'Nível': '',
'EXP': '',
'Claim Reward': '',
'Máximo de jogadores:': '',
'Clique no botão certo para ganhar!': '',
'Erro ao confirmar apelido.': '',
'Definir Apelido': '',
'Confirmar Apelido': '',
'Apelido salvo com sucesso!': '',
'Erro ao salvar apelido.': '',
'Digite seu apelido': '',
'\n': '',
'Minhas Coleções': '',
'email': '',
'Falha na autenticação.': '',
'Houve um problema ao processar o jogo.': '',
'SELECIONE O NÚMERO DE JOGADORES': '',
'JOGADORES': '',
'Escolha o Tipo de Jogo': '',
'Não foi possível encontrar palavras válidas.': '',
'Houve um problema ao buscar as palavras.': '',
'LETRAS': '',
'SELECIONE O NÚMERO DE LETRAS': '',
'Jogo iniciado com sucesso!': '',
'Sala Criada com sucesso!': '',
'Game ID:': '',
'Jogadores conectados:': '',
'Tempo percorrido na fila:': '',
's': '',
'Tempo base na fila:': '',
'Iniciar': '',
'Adicionar Bot': '',
'Sair': '',
'Palavra inválida. Tente novamente.': '',
'Parabéns! Você adivinhou a palavra!': '',
'Última tentativa! Tente adivinhar a palavra.': '',
'Penúltima tentativa! Preste atenção.': '',
'Tentativa incorreta! Continue tentando.': '',
'Comprimento da Palavra: ': '',
'ESCOLHA O IDIOMA': '',
'abrir modal recuperar senha': '',
'vai para signup': '',
'${textContent}': '',