//utils/generateCollections.js

const collectionTitles = [
  "FRUTAS",
  "FERRAMENTAS",
  "CORES",
  "VEÍCULOS",
  "ESPORTES",
  "FILMES",
  "MÚSICAS",
  "LIVROS",
  "JOGOS",
  "LUGARES",
  "CRISTAIS",
  "MINÉRIOS",
  "MONSTROS",
  "AGUARDE...",
];

const COLLECTION_COUNT = collectionTitles.length;

const collections = [
  {
    name: 'collection1',
    fullImage: require('../assets/collections/collection1/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection1/part1.png'),
      part2: require('../assets/collections/collection1/part2.png'),
      part3: require('../assets/collections/collection1/part3.png'),
      part4: require('../assets/collections/collection1/part4.png'),
      part5: require('../assets/collections/collection1/part5.png'),
      part6: require('../assets/collections/collection1/part6.png'),
      part7: require('../assets/collections/collection1/part7.png'),
      part8: require('../assets/collections/collection1/part8.png'),
      part9: require('../assets/collections/collection1/part9.png'),
      part10: require('../assets/collections/collection1/part10.png'),
      part11: require('../assets/collections/collection1/part11.png'),
      part12: require('../assets/collections/collection1/part12.png'),
      part13: require('../assets/collections/collection1/part13.png'),
      part14: require('../assets/collections/collection1/part14.png'),
      part15: require('../assets/collections/collection1/part15.png'),
    },
  },
  {
    name: 'collection2',
    fullImage: require('../assets/collections/collection2/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection2/part1.png'),
      part2: require('../assets/collections/collection2/part2.png'),
      part3: require('../assets/collections/collection2/part3.png'),
      part4: require('../assets/collections/collection2/part4.png'),
      part5: require('../assets/collections/collection2/part5.png'),
      part6: require('../assets/collections/collection2/part6.png'),
      part7: require('../assets/collections/collection2/part7.png'),
      part8: require('../assets/collections/collection2/part8.png'),
      part9: require('../assets/collections/collection2/part9.png'),
      part10: require('../assets/collections/collection2/part10.png'),
      part11: require('../assets/collections/collection2/part11.png'),
      part12: require('../assets/collections/collection2/part12.png'),
      part13: require('../assets/collections/collection2/part13.png'),
      part14: require('../assets/collections/collection2/part14.png'),
      part15: require('../assets/collections/collection2/part15.png'),
    },
  },
  {
    name: 'collection3',
    fullImage: require('../assets/collections/collection3/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection3/part1.png'),
      part2: require('../assets/collections/collection3/part2.png'),
      part3: require('../assets/collections/collection3/part3.png'),
      part4: require('../assets/collections/collection3/part4.png'),
      part5: require('../assets/collections/collection3/part5.png'),
      part6: require('../assets/collections/collection3/part6.png'),
      part7: require('../assets/collections/collection3/part7.png'),
      part8: require('../assets/collections/collection3/part8.png'),
      part9: require('../assets/collections/collection3/part9.png'),
      part10: require('../assets/collections/collection3/part10.png'),
      part11: require('../assets/collections/collection3/part11.png'),
      part12: require('../assets/collections/collection3/part12.png'),
      part13: require('../assets/collections/collection3/part13.png'),
      part14: require('../assets/collections/collection3/part14.png'),
      part15: require('../assets/collections/collection3/part15.png'),
    },
  },
  {
    name: 'collection4',
    fullImage: require('../assets/collections/collection4/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection4/part1.png'),
      part2: require('../assets/collections/collection4/part2.png'),
      part3: require('../assets/collections/collection4/part3.png'),
      part4: require('../assets/collections/collection4/part4.png'),
      part5: require('../assets/collections/collection4/part5.png'),
      part6: require('../assets/collections/collection4/part6.png'),
      part7: require('../assets/collections/collection4/part7.png'),
      part8: require('../assets/collections/collection4/part8.png'),
      part9: require('../assets/collections/collection4/part9.png'),
      part10: require('../assets/collections/collection4/part10.png'),
      part11: require('../assets/collections/collection4/part11.png'),
      part12: require('../assets/collections/collection4/part12.png'),
      part13: require('../assets/collections/collection4/part13.png'),
      part14: require('../assets/collections/collection4/part14.png'),
      part15: require('../assets/collections/collection4/part15.png'),
      part16: require('../assets/collections/collection4/part16.png'),
      part17: require('../assets/collections/collection4/part17.png'),
      part18: require('../assets/collections/collection4/part18.png'),
      part19: require('../assets/collections/collection4/part19.png'),
      part20: require('../assets/collections/collection4/part20.png'),
      part21: require('../assets/collections/collection4/part21.png'),
      part22: require('../assets/collections/collection4/part22.png'),
      part23: require('../assets/collections/collection4/part23.png'),
      part24: require('../assets/collections/collection4/part24.png'),
      part25: require('../assets/collections/collection4/part25.png'),
      part26: require('../assets/collections/collection4/part26.png'),
      part27: require('../assets/collections/collection4/part27.png'),
      part28: require('../assets/collections/collection4/part28.png'),
      part29: require('../assets/collections/collection4/part29.png'),
      part30: require('../assets/collections/collection4/part30.png'),

    },
  },
  {
    name: 'collection5',
    fullImage: require('../assets/collections/collection5/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection5/part1.png'),
      part2: require('../assets/collections/collection5/part2.png'),
      part3: require('../assets/collections/collection5/part3.png'),
      part4: require('../assets/collections/collection5/part4.png'),
      part5: require('../assets/collections/collection5/part5.png'),
      part6: require('../assets/collections/collection5/part6.png'),
      part7: require('../assets/collections/collection5/part7.png'),
      part8: require('../assets/collections/collection5/part8.png'),
      part9: require('../assets/collections/collection5/part9.png'),
      part10: require('../assets/collections/collection5/part10.png'),
      part11: require('../assets/collections/collection5/part11.png'),
      part12: require('../assets/collections/collection5/part12.png'),
      part13: require('../assets/collections/collection5/part13.png'),
      part14: require('../assets/collections/collection5/part14.png'),
      part15: require('../assets/collections/collection5/part15.png'),
      part16: require('../assets/collections/collection5/part16.png'),
    },
  },
  {
    name: 'collection6',
    fullImage: require('../assets/collections/collection6/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection6/part1.png'),
      part2: require('../assets/collections/collection6/part2.png'),
      part3: require('../assets/collections/collection6/part3.png'),
      part4: require('../assets/collections/collection6/part4.png'),
      part5: require('../assets/collections/collection6/part5.png'),
      part6: require('../assets/collections/collection6/part6.png'),
      part7: require('../assets/collections/collection6/part7.png'),
      part8: require('../assets/collections/collection6/part8.png'),
      part9: require('../assets/collections/collection6/part9.png'),
      part10: require('../assets/collections/collection6/part10.png'),
      part11: require('../assets/collections/collection6/part11.png'),
      part12: require('../assets/collections/collection6/part12.png'),
      part13: require('../assets/collections/collection6/part13.png'),
      part14: require('../assets/collections/collection6/part14.png'),
      part15: require('../assets/collections/collection6/part15.png'),
      part16: require('../assets/collections/collection6/part16.png'),
      part17: require('../assets/collections/collection6/part17.png'),
      part18: require('../assets/collections/collection6/part18.png'),
      part19: require('../assets/collections/collection6/part19.png'),
      part20: require('../assets/collections/collection6/part20.png'),
      part21: require('../assets/collections/collection6/part21.png'),
      part22: require('../assets/collections/collection6/part22.png'),
      part23: require('../assets/collections/collection6/part23.png'),
      part24: require('../assets/collections/collection6/part24.png'),
      part25: require('../assets/collections/collection6/part25.png'),
      part26: require('../assets/collections/collection6/part26.png'),
      part27: require('../assets/collections/collection6/part27.png'),
      part28: require('../assets/collections/collection6/part28.png'),
      part29: require('../assets/collections/collection6/part29.png'),
      part30: require('../assets/collections/collection6/part30.png'),
      part31: require('../assets/collections/collection6/part31.png'),
      part32: require('../assets/collections/collection6/part32.png'),
      part33: require('../assets/collections/collection6/part33.png'),
      part34: require('../assets/collections/collection6/part34.png'),
      part35: require('../assets/collections/collection6/part35.png'),
      part36: require('../assets/collections/collection6/part36.png'),
      part37: require('../assets/collections/collection6/part37.png'),
      part38: require('../assets/collections/collection6/part38.png'),
      part39: require('../assets/collections/collection6/part39.png'),
      part40: require('../assets/collections/collection6/part40.png'),
      part41: require('../assets/collections/collection6/part41.png'),
      part42: require('../assets/collections/collection6/part42.png'),
      part43: require('../assets/collections/collection6/part43.png'),
      part44: require('../assets/collections/collection6/part44.png'),
      part45: require('../assets/collections/collection6/part45.png'),
      part46: require('../assets/collections/collection6/part46.png'),
      part47: require('../assets/collections/collection6/part47.png'),
      part48: require('../assets/collections/collection6/part48.png'),
      part49: require('../assets/collections/collection6/part49.png'),
      part50: require('../assets/collections/collection6/part50.png'),
      part51: require('../assets/collections/collection6/part51.png'),
      part52: require('../assets/collections/collection6/part52.png'),
      part53: require('../assets/collections/collection6/part53.png'),
      part54: require('../assets/collections/collection6/part54.png'),
      part55: require('../assets/collections/collection6/part55.png'),
      part56: require('../assets/collections/collection6/part56.png'),
      part57: require('../assets/collections/collection6/part57.png'),
      part58: require('../assets/collections/collection6/part58.png'),
      part59: require('../assets/collections/collection6/part59.png'),
      part60: require('../assets/collections/collection6/part60.png'),
      part61: require('../assets/collections/collection6/part61.png'),
      part62: require('../assets/collections/collection6/part62.png'),
      part63: require('../assets/collections/collection6/part63.png'),
      part64: require('../assets/collections/collection6/part64.png'),
      part65: require('../assets/collections/collection6/part65.png'),
      part66: require('../assets/collections/collection6/part66.png'),
    },
  },
  {
    name: 'collection7',
    fullImage: require('../assets/collections/collection7/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection7/part1.png'),
      part2: require('../assets/collections/collection7/part2.png'),
      part3: require('../assets/collections/collection7/part3.png'),
      part4: require('../assets/collections/collection7/part4.png'),
      part5: require('../assets/collections/collection7/part5.png'),
      part6: require('../assets/collections/collection7/part6.png'),
      part7: require('../assets/collections/collection7/part7.png'),
      part8: require('../assets/collections/collection7/part8.png'),
      part9: require('../assets/collections/collection7/part9.png'),
      part10: require('../assets/collections/collection7/part10.png'),
      part11: require('../assets/collections/collection7/part11.png'),
      part12: require('../assets/collections/collection7/part12.png'),
      part13: require('../assets/collections/collection7/part13.png'),
      part14: require('../assets/collections/collection7/part14.png'),
      part15: require('../assets/collections/collection7/part15.png'),
      part16: require('../assets/collections/collection7/part16.png'),
      part17: require('../assets/collections/collection7/part17.png'),
      part18: require('../assets/collections/collection7/part18.png'),
      part19: require('../assets/collections/collection7/part19.png'),
      part20: require('../assets/collections/collection7/part20.png'),
      part21: require('../assets/collections/collection7/part21.png'),
      part22: require('../assets/collections/collection7/part22.png'),
      part23: require('../assets/collections/collection7/part23.png'),
      part24: require('../assets/collections/collection7/part24.png'),
      part25: require('../assets/collections/collection7/part25.png'),
    },
  },
  {
    name: 'collection8',
    fullImage: require('../assets/collections/collection8/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection8/part1.png'),
      part2: require('../assets/collections/collection8/part2.png'),
      part3: require('../assets/collections/collection8/part3.png'),
      part4: require('../assets/collections/collection8/part4.png'),
      part5: require('../assets/collections/collection8/part5.png'),
      part6: require('../assets/collections/collection8/part6.png'),
      part7: require('../assets/collections/collection8/part7.png'),
      part8: require('../assets/collections/collection8/part8.png'),
      part9: require('../assets/collections/collection8/part9.png'),
      part10: require('../assets/collections/collection8/part10.png'),
      part11: require('../assets/collections/collection8/part11.png'),
      part12: require('../assets/collections/collection8/part12.png'),
      part13: require('../assets/collections/collection8/part13.png'),
      part14: require('../assets/collections/collection8/part14.png'),
      part15: require('../assets/collections/collection8/part15.png'),
      part16: require('../assets/collections/collection8/part16.png'),
      part17: require('../assets/collections/collection8/part17.png'),
      part18: require('../assets/collections/collection8/part18.png'),
      part19: require('../assets/collections/collection8/part19.png'),
      part20: require('../assets/collections/collection8/part20.png'),
      part21: require('../assets/collections/collection8/part21.png'),
      part22: require('../assets/collections/collection8/part22.png'),
      part23: require('../assets/collections/collection8/part23.png'),
      part24: require('../assets/collections/collection8/part24.png'),
      part25: require('../assets/collections/collection8/part25.png'),
      part26: require('../assets/collections/collection8/part26.png'),
      part27: require('../assets/collections/collection8/part27.png'),
      part28: require('../assets/collections/collection8/part28.png'),
      part29: require('../assets/collections/collection8/part29.png'),
      part30: require('../assets/collections/collection8/part30.png'),
      part31: require('../assets/collections/collection8/part31.png'),
      part32: require('../assets/collections/collection8/part32.png'),
      part33: require('../assets/collections/collection8/part33.png'),
      part34: require('../assets/collections/collection8/part34.png'),
      part35: require('../assets/collections/collection8/part35.png'),
      part36: require('../assets/collections/collection8/part36.png'),
      part37: require('../assets/collections/collection8/part37.png'),
      part38: require('../assets/collections/collection8/part38.png'),
      part39: require('../assets/collections/collection8/part39.png'),
      part40: require('../assets/collections/collection8/part40.png'),
    },
  },
  {
    name: 'collection9',
    fullImage: require('../assets/collections/collection9/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection9/part1.png'),
      part2: require('../assets/collections/collection9/part2.png'),
      part3: require('../assets/collections/collection9/part3.png'),
      part4: require('../assets/collections/collection9/part4.png'),
      part5: require('../assets/collections/collection9/part5.png'),
      part6: require('../assets/collections/collection9/part6.png'),
      part7: require('../assets/collections/collection9/part7.png'),
      part8: require('../assets/collections/collection9/part8.png'),
      part9: require('../assets/collections/collection9/part9.png'),
      part10: require('../assets/collections/collection9/part10.png'),
      part11: require('../assets/collections/collection9/part11.png'),
      part12: require('../assets/collections/collection9/part12.png'),
      part13: require('../assets/collections/collection9/part13.png'),
      part14: require('../assets/collections/collection9/part14.png'),
      part15: require('../assets/collections/collection9/part15.png'),
      part16: require('../assets/collections/collection9/part16.png'),
      part17: require('../assets/collections/collection9/part17.png'),
      part18: require('../assets/collections/collection9/part18.png'),
      part19: require('../assets/collections/collection9/part19.png'),
      part20: require('../assets/collections/collection9/part20.png'),
    },
  },
  {
    name: 'collection10',
    fullImage: require('../assets/collections/collection10/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection10/part1.png'),
      part2: require('../assets/collections/collection10/part2.png'),
      part3: require('../assets/collections/collection10/part3.png'),
      part4: require('../assets/collections/collection10/part4.png'),
      part5: require('../assets/collections/collection10/part5.png'),
      part6: require('../assets/collections/collection10/part6.png'),
      part7: require('../assets/collections/collection10/part7.png'),
      part8: require('../assets/collections/collection10/part8.png'),
      part9: require('../assets/collections/collection10/part9.png'),
      part10: require('../assets/collections/collection10/part10.png'),
      part11: require('../assets/collections/collection10/part11.png'),
      part12: require('../assets/collections/collection10/part12.png'),
      part13: require('../assets/collections/collection10/part13.png'),
      part14: require('../assets/collections/collection10/part14.png'),
      part15: require('../assets/collections/collection10/part15.png'),
      part16: require('../assets/collections/collection10/part16.png'),
      part17: require('../assets/collections/collection10/part17.png'),
      part18: require('../assets/collections/collection10/part18.png'),
      part19: require('../assets/collections/collection10/part19.png'),
      part20: require('../assets/collections/collection10/part20.png'),
      part21: require('../assets/collections/collection10/part21.png'),
      part22: require('../assets/collections/collection10/part22.png'),
      part23: require('../assets/collections/collection10/part23.png'),
      part24: require('../assets/collections/collection10/part24.png'),
    },
  },
  {
    name: 'collection11',
    fullImage: require('../assets/collections/collection11/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection11/part1.png'),
      part2: require('../assets/collections/collection11/part2.png'),
      part3: require('../assets/collections/collection11/part3.png'),
      part4: require('../assets/collections/collection11/part4.png'),
      part5: require('../assets/collections/collection11/part5.png'),
      part6: require('../assets/collections/collection11/part6.png'),
      part7: require('../assets/collections/collection11/part7.png'),
      part8: require('../assets/collections/collection11/part8.png'),
      part9: require('../assets/collections/collection11/part9.png'),
      part10: require('../assets/collections/collection11/part10.png'),
      part11: require('../assets/collections/collection11/part11.png'),
      part12: require('../assets/collections/collection11/part12.png'),
      part13: require('../assets/collections/collection11/part13.png'),
      part14: require('../assets/collections/collection11/part14.png'),
      part15: require('../assets/collections/collection11/part15.png'),
    },
  },
  {
    name: 'collection12',
    fullImage: require('../assets/collections/collection12/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection12/part1.png'),
      part2: require('../assets/collections/collection12/part2.png'),
      part3: require('../assets/collections/collection12/part3.png'),
      part4: require('../assets/collections/collection12/part4.png'),
      // part5: require('../assets/collections/collection12/part5.png'),
      // part6: require('../assets/collections/collection12/part6.png'),
      // part7: require('../assets/collections/collection12/part7.png'),
      // part8: require('../assets/collections/collection12/part8.png'),
      // part9: require('../assets/collections/collection12/part9.png'),
      // part10: require('../assets/collections/collection12/part10.png'),
      // part11: require('../assets/collections/collection12/part11.png'),
      // part12: require('../assets/collections/collection12/part12.png'),
      // part13: require('../assets/collections/collection12/part13.png'),
      // part14: require('../assets/collections/collection12/part14.png'),
      // part15: require('../assets/collections/collection12/part15.png'),
    },
  },
  {
    name: 'collection13',
    fullImage: require('../assets/collections/collection13/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection13/part1.png'),
      part2: require('../assets/collections/collection13/part2.png'),
      part3: require('../assets/collections/collection13/part3.png'),
      part4: require('../assets/collections/collection13/part4.png'),
      part5: require('../assets/collections/collection13/part5.png'),
      part6: require('../assets/collections/collection13/part6.png'),
      part7: require('../assets/collections/collection13/part7.png'),
      part8: require('../assets/collections/collection13/part8.png'),
      part9: require('../assets/collections/collection13/part9.png'),
      part10: require('../assets/collections/collection13/part10.png'),
      part11: require('../assets/collections/collection13/part11.png'),
      part12: require('../assets/collections/collection13/part12.png'),
      part13: require('../assets/collections/collection13/part13.png'),
      part14: require('../assets/collections/collection13/part14.png'),
      part15: require('../assets/collections/collection13/part15.png'),
    },
  },
  {
    name: 'collection14',
    fullImage: require('../assets/collections/collection14/fullimage.png'),
    parts: {
      part1: require('../assets/collections/collection14/part1.png'),
      part2: require('../assets/collections/collection14/part2.png'),
      part3: require('../assets/collections/collection14/part3.png'),
      part4: require('../assets/collections/collection14/part4.png'),
      part5: require('../assets/collections/collection14/part5.png'),
      part6: require('../assets/collections/collection14/part6.png'),
      part7: require('../assets/collections/collection14/part7.png'),
      part8: require('../assets/collections/collection14/part8.png'),
      part9: require('../assets/collections/collection14/part9.png'),
      part10: require('../assets/collections/collection14/part10.png'),
      part11: require('../assets/collections/collection14/part11.png'),
      part12: require('../assets/collections/collection14/part12.png'),
      part13: require('../assets/collections/collection14/part13.png'),
      part14: require('../assets/collections/collection14/part14.png'),
      part15: require('../assets/collections/collection14/part15.png'),
    },
  },
];

const getCollectionEarnedFull = (collectionName, itemName) => {
  // console.log("testes");
  // console.log(collectionName);
  // console.log(itemName);
  const collection = collections.find(col => col.name === collectionName);
  if (!collection) {
    return null;
  }

  const item = collection.parts[itemName];
  if (!item) {
    return null;
  }

  // Encontra o título da coleção com base no índice da coleção encontrada
  const collectionIndex = collections.indexOf(collection);
  // console.log("collectionIndex");
  // console.log(collectionIndex);
  const collectionTitle = collectionTitles[collectionIndex];

  return {
    collectionName: collectionTitle,
    itemImage: item,
  };
};

export { collections, collectionTitles, COLLECTION_COUNT, getCollectionEarnedFull };
