// Arquivo: utils/translate.js

const translations = {
    pt: {
        'BEM VINDO': 'BEM VINDO',
        'USUÁRIO': 'USUÁRIO',
        'DESAFIE AMIGOS': 'DESAFIE AMIGOS',
        'USUÁRIO NÃO ENCONTRADO': 'USUÁRIO NÃO ENCONTRADO',
        'JOGAR': 'JOGAR',
        'COLEÇÕES': 'COLEÇÕES',
        'ESCOLHER PALAVRA': 'ESCOLHER PALAVRA',
        'IDIOMA': 'IDIOMA',
        'INFORMAÇÕES': 'INFORMAÇÕES',
        'ESCOLHA O IDIOMA': 'ESCOLHA O IDIOMA',
        'LETRAS': 'LETRAS',
        'TIPO DE JOGO': 'TIPO DE JOGO',
        'Não foi possível encontrar palavras válidas.': 'Não foi possível encontrar palavras válidas.',
        'Erro': 'Erro',
        'Informações do App': 'Informações do App',
        'Este aplicativo utiliza imagens geradas por IA através do Stable Diffusion.': 'Este aplicativo utiliza imagens geradas por IA através do Stable Diffusion.',
        'Para quaisquer questões ou problemas, entre em contato com o desenvolvedor.': 'Para quaisquer questões ou problemas, entre em contato com o desenvolvedor.',
        'Email: maxsk.ltda@gmail.com': 'Email: maxsk.ltda@gmail.com',
        'Falha na autenticação.': 'Falha na autenticação.',
        'letras.': 'letras.',
        'Por favor, insira uma palavra válida com': 'Por favor, insira uma palavra válida com',
        'Tentativa incorreta! Continue tentando. Tentativas restantes:': 'Tentativa incorreta! Continue tentando. Tentativas restantes:',
        'Letra correta! Continue tentando.': 'Letra correta! Continue tentando.',
        'Parabéns! Você adivinhou a palavra!': 'Parabéns! Você adivinhou a palavra!',
        'Você perdeu! A palavra era: ': 'Você perdeu! A palavra era: ',
        'Palavra inválida. Tente novamente.': 'Palavra inválida. Tente novamente.',
        'Comprimento da Palavra: ': 'Comprimento da Palavra: ',
        'Última tentativa! Tente adivinhar a palavra.': 'Última tentativa! Tente adivinhar a palavra.',
        'Definir Apelido': 'Definir Apelido',
        'Digite seu apelido': 'Digite seu apelido',
        'Apelido salvo com sucesso!': 'Apelido salvo com sucesso!',
        'Apelido já existe.': 'Apelido já existe.',
        'Erro ao verificar apelido.': 'Erro ao verificar apelido.',
        'Erro ao salvar apelido.': 'Erro ao salvar apelido.',
        'Houve um problema ao processar o jogo.': 'Houve um problema ao processar o jogo.',
        'JOGADORES': 'JOGADORES',
        'SELECIONE O NÚMERO DE JOGADORES': 'SELECIONE O NÚMERO DE JOGADORES',
        'Escolha o Tipo de Jogo': 'Escolha o Tipo de Jogo',
        'Conectados': 'Conectados',
        'Usuário não autenticado ou ID de jogo não fornecido.': 'Usuário não autenticado ou ID de jogo não fornecido.',
        's': 's',
        'Jogo iniciado com sucesso!': 'Jogo iniciado com sucesso!',
        'Jogadores conectados:': 'Jogadores conectados:',
        'Tempo base na fila:': 'Tempo base na fila:',
        'Tempo percorrido na fila:': 'Tempo percorrido na fila:',
        'Ativar jogo com bots': 'Ativar jogo com bots',
        'Adicionar Bot': 'Adicionar Bot',
        'Sair da fila': 'Sair da fila',
        'Carregando...': 'Carregando...',
        'Ocorreu um problema ao inicializar o jogo. Por favor, tente novamente.': 'Ocorreu um problema ao inicializar o jogo. Por favor, tente novamente.',
        'Não foi possível iniciar o jogo. Por favor, verifique sua conexão e tente novamente.': 'Não foi possível iniciar o jogo. Por favor, verifique sua conexão e tente novamente.',
        'Tentar novamente': 'Tentar novamente',
        'Sala Criada com sucesso!': 'Sala Criada com sucesso!',
        'Dados do Jogador': 'Dados do Jogador',
        'Nome': 'Nome',
        'Conectados': 'Conectados',
        'Dados dos Jogadores': 'Dados dos Jogadores',
        'Minhas Coleções': 'Minhas Coleções',
        'FRUTAS': 'FRUTAS',
        'FERRAMENTAS': 'FERRAMENTAS',
        'CORES': 'CORES',
        'VEÍCULOS': 'VEÍCULOS',
        'ESPORTES': 'ESPORTES',
        'FILMES': 'FILMES',
        'MÚSICAS': 'MÚSICAS',
        'LIVROS': 'LIVROS',
        'JOGOS': 'JOGOS',
        'LUGARES': 'LUGARES',
        'CRISTAIS': 'CRISTAIS',
        'MINÉRIOS': 'MINÉRIOS',
        'MONSTROS': 'MONSTROS',
        'AGUARDE...': 'AGUARDE...',
        'Trilha de EXP': 'Trilha de EXP',
        'Nível': 'Nível',
        'Máximo de jogadores:': 'Máximo de jogadores:',
        'Fechar': 'Fechar',
        'Clique no botão certo para ganhar!': 'Clique no botão certo para ganhar!',
        'Recompensa:': 'Recompensa:',
        'Colecionável Recebido!': '',
        'Coleção:': 'Coleção:',
        'Nome': 'Nome',
        'Conectados': 'Conectados',
        'Nenhum jogador encontrado.': 'Nenhum jogador encontrado.',
        'Dados do jogo não encontrados.': 'Dados do jogo não encontrados.',
        'Houve um problema ao buscar os dados do jogo.': 'Houve um problema ao buscar os dados do jogo.',
        'Nenhum jogador disponível': 'Nenhum jogador disponível',
        'Dados dos Jogadores': 'Dados dos Jogadores',
        'EXP': 'EXP',
        'Pegar Recompensa': 'Pegar Recompensa',
        'Erro ao confirmar apelido.': 'Erro ao confirmar apelido.',
        'Confirmar Apelido': 'Confirmar Apelido',
        'Houve um problema ao buscar as palavras.': 'Houve um problema ao buscar as palavras.',
        'SELECIONE O NÚMERO DE LETRAS': 'SELECIONE O NÚMERO DE LETRAS',
        'Iniciar': 'Iniciar',
        'Penúltima tentativa! Preste atenção.': 'Penúltima tentativa! Preste atenção.',
        'abrir modal recuperar senha': 'abrir modal recuperar senha',
        'vai para signup': 'vai para signup',
        'Você Ganhou!': 'Você Ganhou!',
        'Você Perdeu! Mas ainda ganhou:': 'Você Perdeu! Mas ainda ganhou:',
        'Recompensas do Mini Jogo': 'Recompensas do Mini Jogo',
        'Selecione um Mini Jogo': 'Selecione um Mini Jogo',
        'Começar Mini Jogo': 'Começar Mini Jogo',
        'Ver Recompensas': 'Ver Recompensas',
        'Minhas Coleções': 'Minhas Coleções',
        'Dev Tools': 'Ferramentas de Desenvolvedor',
        'Add 1000 Coins': 'Adicionar 1000 Moedas',
        'Add 1 Key': 'Adicionar 1 Chave',
        'Add 1 Super Key': 'Adicionar 1 Super Chave',
        'Add 500 WordPoints': 'Adicionar 500 WordPoints',
        'Reset Chest Timer': 'Resetar Temporizador do Baú',
        'Reset All Resources': 'Resetar Todos os Recursos',
        'Max All Resources': 'Maximizar Todos os Recursos',
        'Termax': 'Termax',
        'TERMAX': 'TERMAX',
        'Usuário: ': 'Usuário: ',
        'Usuário não encontrado': 'Usuário não encontrado',
        'Carregando...': 'Carregando...',
        'Escolha uma Palavra': 'Escolha uma Palavra',
        'Termax': 'Termax',
        'Recompensas do Baú': 'Recompensas do Baú',
        'Baú Normal:': 'Baú Normal:',
        '100 - 1000 Coins': '100 - 1000 Coins',
        'Baú Especial:': 'Baú Especial:',
        '1000 - 10000 Coins': '1000 - 10000 Coins',
        'Ambos podem conter:': 'Ambos podem conter:',
        'Wordpoints': 'Wordpoints',
        'Jogando...': 'Jogando...',
        'Loja': 'Loja',
        'Jogar Mini Game': 'Jogar Mini Game',
        'TELA EM MANUTENÇÃO': 'TELA EM MANUTENÇÃO',
        'EM BREVE PODERÁ ACESSAR A FUNCIONALIDADE DO SISTEMA:': 'EM BREVE PODERÁ ACESSAR A FUNCIONALIDADE DO SISTEMA:',
        'Perfil do Usuário': 'Perfil do Usuário',
        'OU': 'OU',
        'Não tem uma conta?': 'Não tem uma conta?',
        'PORTUGUÊS': 'PORTUGUÊS',
        'INGLÊS': 'INGLÊS',
        'Português': 'Português',
        'Inglês': 'Inglês',
        'Open Free Chest': 'Abrir Baú Gratuito',
        'Open Normal Chest': 'Abrir Baú Normal',
        'Open Special Chest': 'Abrir Baú Especial',
        'Max All Resources': 'Maximizar Todos os Recursos',
        'Próximo baú gratuito em:': 'Próximo baú gratuito em:',
        'Próximo mini jogo disponível em:': 'Próximo mini jogo disponível em:',
        'Mini Jogo': 'Mini Jogo',
        'Mini Jogos': 'Mini Jogos',
        'Premio Máximo:': 'Premio Máximo:',
        'Nível': 'Nível',
    },
    en: {
        'BEM VINDO': 'WELCOME',
        'USUÁRIO': 'USER',
        'DESAFIE AMIGOS': 'CHALLENGE FRIENDS',
        'USUÁRIO NÃO ENCONTRADO': 'USER NOT FOUND',
        'JOGAR': 'PLAY',
        'COLEÇÕES': 'COLLECTIONS',
        'ESCOLHER PALAVRA': 'CHOOSE WORD',
        'IDIOMA': 'LANGUAGE',
        'INFORMAÇÕES': 'INFO',
        'ESCOLHA O IDIOMA': 'CHOOSE YOUR LANGUAGE',
        'LETRAS': 'LETTERS',
        'TIPO DE JOGO': 'GAME TYPE',
        'Não foi possível encontrar palavras válidas.': 'Could not find valid words',
        'Erro': 'Error',
        'Informações do App': 'App Information',
        'Este aplicativo utiliza imagens geradas por IA através do Stable Diffusion.': 'This application uses AI-generated images through Stable Diffusion.',
        'Para quaisquer questões ou problemas, entre em contato com o desenvolvedor.': 'For any questions or problems, please contact the developer.',
        'Email: maxsk.ltda@gmail.com': 'Email: maxsk.ltda@gmail.com',
        'Falha na autenticação.': 'Authentication failed.',
        'letras.': 'letters.',
        'Por favor, insira uma palavra válida com': 'Please enter a valid word with',
        'Tentativa incorreta! Continue tentando. Tentativas restantes:': 'Incorrect attempt! Try again. Remaining attempts:',
        'Letra correta! Continue tentando.': 'Correct letter! Keep trying.',
        'Parabéns! Você adivinhou a palavra!': 'Congratulations! You guessed the word!',
        'Você perdeu! A palavra era: ': 'You lost! The word was:',
        'Palavra inválida. Tente novamente.': 'Invalid word. Try again.',
        'Comprimento da Palavra: ': 'Word Length: ',
        'Última tentativa! Tente adivinhar a palavra.': 'Last try! Try to guess the word.',
        'Definir Apelido': 'Put your nickname',
        'Digite seu apelido': 'Put your nickname',
        'Apelido salvo com sucesso!': 'Nickname save with success!',
        'Apelido já existe.': 'Nickname already exists.',
        'Erro ao verificar apelido.': 'Error to verificate nickname.',
        'Erro ao salvar apelido.': 'Error to save nickname.',
        'Houve um problema ao processar o jogo.': 'There was a problem processing the game.',
        'JOGADORES': 'PLAYERS',
        'SELECIONE O NÚMERO DE JOGADORES': 'SELECT THE NUMBER OF PLAYERS',
        'Escolha o Tipo de Jogo': 'Choose Game Type',
        'Conectados': 'Connected',
        'Usuário não autenticado ou ID de jogo não fornecido.': 'User not autenticated or ID game not provided.',
        's': 's',
        'Jogo iniciado com sucesso!': 'Game loaded with success!',
        'Jogadores conectados:': 'Players connect:',
        'Tempo base na fila:': 'Base time in queue:',
        'Tempo percorrido na fila:': 'Time spent in queue:',
        'Ativar jogo com bots': 'Active match with Bots',
        'Adicionar Bot': 'Add Bot',
        'Sair da fila': 'Leave',
        'Carregando...': 'Loading...',
        'Ocorreu um problema ao inicializar o jogo. Por favor, tente novamente.': 'There was a problem initializing the game. Please try again.',
        'Não foi possível iniciar o jogo. Por favor, verifique sua conexão e tente novamente.': 'Could not start the game. Please check your connection and try again.',
        'Tentar novamente': 'Try again.',
        'Sala Criada com sucesso!': 'Room created with Success!',
        'Dados do Jogador': 'Player Data',
        'Nome': 'Name',
        'Conectados': 'Conected',
        'Dados dos Jogadores': 'Data Players',
        'Minhas Coleções': 'My collections',
        'FRUTAS': 'FRUITS',
        'FERRAMENTAS': 'TOOLS',
        'CORES': 'COLORS',
        'VEÍCULOS': 'VEHICLES',
        'ESPORTES': 'SPORTS',
        'FILMES': 'MOVIES',
        'MÚSICAS': 'MUSIC',
        'LIVROS': 'BOOKS',
        'JOGOS': 'GAMES',
        'LUGARES': 'PLACES',
        'CRISTAIS': 'CRYSTALS',
        'MINÉRIOS': 'ORE',
        'MONSTROS': 'MONSTERS',
        'AGUARDE...': 'COMING SOON',
        'Trilha de EXP': 'EXP Trail',
        'Nível': 'Level',
        'Máximo de jogadores:': 'Players Capacity:',
        'Fechar': 'Close',
        'Clique no botão certo para ganhar!': 'Click on the correct button to win!',
        'Recompensa:': 'Reward:',
        'Coleção:': 'Collection:',
        'Nome': 'Name',
        'Conectados': 'Connected',
        'Nenhum jogador encontrado.': 'No players found.',
        'Dados do jogo não encontrados.': 'Game data not found.',
        'Houve um problema ao buscar os dados do jogo.': 'There was a problem retrieving the game data.',
        'Nenhum jogador disponível': 'No players available',
        'Dados dos Jogadores': 'Player Data',
        'EXP': 'EXP',
        'Pegar Recompensa': 'Claim Reward',
        'Erro ao confirmar apelido.': 'Error confirming nickname.',
        'Confirmar Apelido': 'Confirm Nickname',
        'Houve um problema ao buscar as palavras.': 'There was a problem retrieving the words.',
        'SELECIONE O NÚMERO DE LETRAS': 'SELECT THE NUMBER OF LETTERS',
        'Iniciar': 'Start',
        'Penúltima tentativa! Preste atenção.': 'Penultimate attempt! Pay attention.',
        'abrir modal recuperar senha': 'open modal to recover password',
        'vai para signup': 'go to signup',
        'Você Ganhou!': 'You Won!',
        'Você Perdeu! Mas ainda ganhou:': 'You Lost! But you still won:',
        'Recompensas do Mini Jogo': 'Mini Game Rewards',
        'Dev Tools': 'Dev Tools',
        '(parseInt(game.id) * 100) + 100(parseInt(game.id) * 100) + 500': '(parseInt(game.id) * 100) + 100(parseInt(game.id) * 100) + 500',
        'Selecione um Mini Jogo': 'Select a MiniGame',
        'Começar Mini Jogo': 'Start MiniGame',
        'Ver Recompensas': 'View Rewards',
        'Fechar': 'Close',
        'Fechar': 'Close',
        '&lt; voltar': '&lt; back',
        '&lt; voltar': '&lt; back',
        'Minhas Coleções': 'My Collections',
        'Add 1000 Coins': 'Add 1000 Coins',
        'Add 1 Key': 'Add 1 Key',
        'Add 1 Super Key': 'Add 1 Super Key',
        'Add 500 WordPoints': 'Add 500 WordPoints',
        'Reset Chest Timer': 'Reset Chest Timer',
        'Reset All Resources': 'Reset All Resources',
        'Max All Resources': 'Max All Resources',
        'Termax': 'Termax',
        'TERMAX': 'TERMAX',
        'Usuário: ': 'User: ',
        'Usuário não encontrado': 'User not found',
        'Escolha uma Palavra': 'Choose a Word',
        'Termax': 'Termax',
        'Recompensas do Baú': 'Chest Rewards',
        'Baú Normal:': 'Normal Chest:',
        '100 - 1000 Coins': '100 - 1000 Coins',
        'Baú Especial:': 'Special Chest:',
        '1000 - 10000 Coins': '1000 - 10000 Coins',
        'Ambos podem conter:': 'Both may contain:',
        'Wordpoints': 'Wordpoints',
        'Loja': 'Shop',
        'Jogar Mini Game': 'Play Mini Game',
        'TELA EM MANUTENÇÃO': 'SCREEN UNDER MAINTENANCE',
        'EM BREVE PODERÁ ACESSAR A FUNCIONALIDADE DO SISTEMA:': 'SOON YOU WILL BE ABLE TO ACCESS THE SYSTEM FUNCTIONALITY:',
        'Perfil do Usuário': 'User Profile',
        'OU': 'OR',
        'Não tem uma conta?': 'Dont have an account?',
        'Jogando...': 'Playing...',
        'PORTUGUÊS': 'PORTUGUESE',
        'INGLÊS': 'ENGLISH',
        'Português': 'Portuguese',
        'Inglês': 'English',
        'Open Free Chest': 'Open Free Chest',
        'Open Normal Chest': 'Open Normal Chest',
        'Open Special Chest': 'Open Special Chest',
        'Max All Resources': 'Max All Resources',
        'Próximo baú gratuito em:': 'Next free chest:',
        'Próximo mini jogo disponível em:': 'Next minigame:',
        'Mini Jogo': 'Minigame',
        'Mini Jogos': 'Minigames',
        'Premio Máximo:': 'Max Reward',
        'Nível': 'Level',
    },
};

export { translations };